demo/app/urls.py
from unicodedata import name
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('sign-in', views.sign_in, name='sign_in'),
    path('sign-up', views.sign_up, name='sign_up'),
    path('sign-out', views.sign_out, name='sign_out'),

    path('product/<int:id>', views.product_detail, name='product_detail'),

    path('cart/', views.cart, name='cart'),
    path('addToCart/', views.addToCart, name='addToCart'),
    path('cartPlus/', views.cartPlus, name='cartPlus'),
    path('cartMinus/', views.cartMinus, name='cartMinus'),

    path('new-order/', views.new_order, name='new_order'),
    path('order-detail/<int:id>/', views.order_detail, name='order_detail'),


    path('settings/index.html', views.settings, name='settings'),


    # Admin panel
    path('user/product', views.admin_product, name='admin_product'),
    path('user/product-image/<int:id>/', views.admin_product_image_edit, name='admin_product_image_edit'),

    path('user/product-color/<int:id>', views.admin_product_detail, name='admin_product_detail'),
    path('user/create/product', views.product_create, name='product_create'),
    
    # Product Color 
    path('user/create/productColor/<int:id>/', views.productColor_create, name='productColor_create'),
    path('user/delete/productColor/<int:id>/', views.productColor_delete, name='productColor_delete'),

    # Product Color size
    path('user/create/productColorSize/<int:id>/', views.productColorSize_create, name='productColorSize_create'),
    path('user/delete/productColorSize/', views.productColorSize_delete, name='productColorSize_delete'),
    path('user/edit/productColorSize/', views.productColorSize_edit, name='productColorSize_edit'),


    # Product Color Size Gallery

    path('user/gallery/productColor/<int:id>/', views.productColor_gallery, name='productColor_gallery'),
    path('user/gallery/productColor/<int:id>/create', views.productColor_gallery_create, name='productColor_gallery_create'),
    path('user/gallery/productColor/remove', views.productColor_gallery_remove, name='productColor_gallery_remove'),

    # Storage
    path('storage/', views.storage, name='storage'),
    path('storage-detail/<int:id>/', views.storage_detail, name='storage_detail'),
    path('storage/<int:id>/', views.storage_reload, name='storage_reload')




    
]

demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

demo/app/models.py
from tabnanny import verbose
from django.utils import timezone
from django.db import models
from django.conf import settings
User = settings.AUTH_USER_MODEL



class Category(models.Model):
    title = models.CharField('Категория товара', max_length=256)
    icon = models.ImageField('Иконка', upload_to='category_icons', blank=True)


    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


class Brand(models.Model):
    title = models.CharField('Бренд товара', max_length=256)
    image = models.ImageField('Логотип', upload_to='product_logos', blank=True)


    class Meta:
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренды'

    def __str__(self):
        return self.title


class Color(models.Model):
    title = models.CharField('Цвет', max_length=256)
    code = models.CharField('Hex', max_length=256, null=True)


    class Meta:
        verbose_name = 'Цвет'
        verbose_name_plural = 'Цвета'

    def __str__(self):
        return self.title



class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория', related_name='category_products')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, verbose_name='Бренд', related_name='brand_products')
    title = models.CharField('Название товара', max_length=256)
    text = models.TextField('Описание')
    year = models.IntegerField(default=0)
    image = models.ImageField('Фото', upload_to='product_image', blank=True)
    created_at = models.DateTimeField('Дата создания',default=timezone.now())
    color = models.ManyToManyField(Color, verbose_name='Цвет', through="ProductColor")



    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты(общий)'

    def __str__(self):
        return self.title


    
class Memory(models.Model):
    size = models.IntegerField('Память', default=0)


    class Meta:
        verbose_name = 'Память'
        verbose_name_plural = 'Память'

    def __str__(self):
        return str(self.size)




class ProductColor(models.Model):
    color = models.ForeignKey(Color, on_delete=models.CASCADE, verbose_name='Цвет', related_name='color_products')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')


    class Meta:
        verbose_name = 'Product color'
        verbose_name_plural = 'Product color'

    def __str__(self):
        return self.product.title + ' ' + self.color.title


class ProductGallery(models.Model):
    productColor = models.ForeignKey(ProductColor, on_delete=models.CASCADE, verbose_name='Продукт', related_name='gallery_products')
    image = models.ImageField('Фото продукта', upload_to='productColor_gallery', blank=True)

    class Meta:
        verbose_name = 'Галерея'
        verbose_name_plural = 'Галерея'

    def __str__(self):
        return self.productColor.product.title


class ProductColorSize(models.Model):
    productColor = models.ForeignKey(ProductColor, on_delete=models.CASCADE, verbose_name='Продукт', related_name='product_productsColors')
    memory = models.ForeignKey(Memory, null=True,  on_delete=models.CASCADE, verbose_name='Память', related_name='memory_productsColors')
    price = models.IntegerField('Цена', default=0)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


    def real_count(self):
        income = sum([storage.quantity for storage in self.storage_set.filter(storage_type = True)])
        consumption = sum([storage.quantity for storage in self.storage_set.filter(storage_type = False)])
        result = income - consumption
        return result

    def __str__(self):
        return  str(self.productColor.product) + ' ' + str(self.memory)+ 'GB' + ' ' + str(self.productColor.color.title)



class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Юзер', related_name='user_carts' )
    product = models.ForeignKey(ProductColorSize, on_delete=models.CASCADE, verbose_name='Продукт', related_name='cart_products')
    quantity = models.IntegerField('Кол-во', default=0)

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзина'

    def __str__(self):
        return str(self.user) + " " + str(self.product)



class Order(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, verbose_name='Юзер', related_name='user_orders' )
    total = models.IntegerField('Total', default=0)
    status = models.BooleanField('Status', default=False)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказ'

    def __str__(self):
        return str(self.user) 


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete = models.CASCADE)
    product = models.ForeignKey(ProductColorSize, on_delete = models.SET_NULL, null=True)
    product_count = models.IntegerField('Количество', default=0)

    class Meta:
        verbose_name = 'Order Product'
        verbose_name_plural = 'Order Product'

    def __str__(self):
        return str(self.product) 



class Storage(models.Model):
    quantity = models.IntegerField('Кол-во товара в наличии', default = 0)  
    productColorSize = models.ForeignKey(ProductColorSize, on_delete = models.SET_NULL,   null=True, verbose_name="Продукт")   
    storage_type = models.BooleanField(default=False) 
    date = models.DateTimeField('Дата', default = timezone.now)

demo/app/templates/pages/admin/color-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Settings {% endblock %}

{% block content %}
   <!-- Main -->
<div class="bg-light settings-page vh-100 bg-sm-none ">
    <div class="container py-4">
        {% include 'pages/settings/menu.html' %}
        <div class=" bg-white shadow-2 rounded-1 p-4 mt-4 p-sm-0 ">
            <div class="d-flex align-items-center justify-content-between">
                <div class="fs-30 b-1">Продукты</div>
                <div class="d-flex">
                    <button class="btn btn-green rounded-1 addProductColor">Добавить цвет</button>
                    <form action="{% url 'productColor_create' product.id %}" class="d-flex ml-3 d-none addProductColorContainer" method="POST">
                        {% csrf_token %}
                        <select class="input " name="colorId" id="">
                            {% for color in colors %}
                                <option class="colorsSelect " value="{{color.id}}">{{color.title}}</option>
                            {% endfor %}
                        </select>
                        <button class="btn btn-green rounded-1 ml-3">Добавить</button>
                    </form>
                </div>
            </div>
            <div class="hr-dark-light"></div>
             
            <div class="grid-4 gap-1">
                {% for item in product.productcolor_set.all %}
                   <div class="p-3 border-dark-light rounded-1">
                    {{item}}
                   </div>
                {% endfor %}
            </div>

    
        </div>
    </div>
</div>

{% endblock %}

demo/app/templates/pages/admin/create-product.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Settings {% endblock %}

{% block content %}
   <!-- Main -->


    <div class="bg-light settings-page min-vh-100 bg-sm-none">
        <div class="container py-4">
 
            <form action=""  class="w-50 shadow-2 bg-white  mx-auto rounded-1 p-4 mt-4 p-sm-0 " method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="fs-30 b-2 text-center">Создание продукта</div>
                
                    <div class="hr-dark-light"></div>
                    <div class="grid-2 gap-1" >
                        <div class="">
                            <label class="label" for="">Категория</label>
                            <select class="category w-100" name="category">
                                {% for category in categories %}
                                <option value="{{category.id}}">{{category.title}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="">
                            <label class="label" for="">Фирма</label>
                            <select class="category w-100" name="brand">
                                {% for brand in brands %}
                                <option value="{{brand.id}}">{{brand.title}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="">
                            <label class="label" for="">Название</label>
                            <input class="input input-sm" name="title" type="text">
                        </div>
                        <div class="">
                            <label class="label" for="">Год выпуска</label>
                            <input class="input input-sm" name="year" type="number">
                        </div>
                        
                    </div>
                    <div class="grid-1 gap-1 mt-4">
                        <div class="">
                            <label class="label" for="">Фото</label>
                            <input class="input input-sm" name="image" type="file">
                        </div>
                        <div class="">
                            <label class="label" for="">Цвет</label>
                            <select class="colors w-100" name="colors[]" multiple="multiple">
                                {% for color in colors %}
                                    <option value="{{color.id}}">{{color.title}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <textarea placeholder="Описание товара" style="height: 150px;" name="text" class="input mt-4"></textarea>
                    <button class="btn btn-blue mx-auto rounded-1 mt-4 w-50">Добавить</button>
            </form>
        </div>
    </div>


{% endblock %}

demo/app/templates/pages/admin/product-detail-gallery.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Settings {% endblock %}

{% block content %}
   <!-- Main -->

   
    <div class="bg-light settings-page min-vh-100 bg-sm-none">
        <div class="container py-4">
            <div class="bg-white py-4 px-3 rounded-1">
                <div class="grid-6 gap-1">
                    {% for item in gallery %}
                    <div class="p-3 shadow-2 galleryItem">
                        <button data-url="{% url 'productColor_gallery_remove' %}" data-colorId="{{productColor.id}}" data-imageId="{{item.id}}" class="btn btn-red btnGalleryRemove">D</button>
                        <img class="w-100 object-fit" src="{{item.image.url}}" alt="">
                    </div>
                    {% endfor %}
                </div>
                <button  class="addImage btn btn-yellow rounded-1 mb-4 mt-5">Добавить фото</button>

                <form action="{% url 'productColor_gallery_create' productColor.id %}" class="inputFileContainer grid-1 gap-1" enctype="multipart/form-data" method="POST" >
                    {% csrf_token %}
                    <button class="d-none btn btn-blue w-50 rounded-1">Добавить</button>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

demo/app/templates/pages/admin/product-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Settings {% endblock %}

{% block content %}
   <!-- Main -->
<div class="bg-light settings-page vh-100 bg-sm-none ">
    <div class="container py-4">
        {% include 'pages/settings/menu.html' %}
        <div class=" bg-white shadow-2 rounded-1 p-4 mt-4 p-sm-0 ">
            <div class="d-flex align-items-center justify-content-between">
                <div class="fs-30 b-1">Продукты</div>
                <div class="d-flex">
                    <button class="btn btn-green rounded-1 addProductColor">Добавить память</button>
                    <form action="{% url 'productColorSize_create' productColor.id %}" class="d-flex ml-3 d-none addProductColorContainer" method="POST">
                        {% csrf_token %}
                        <input class="input mr-3" name="price" placeholder="Цена" type="number">
                        <select class="input colorsSelectContainer" name="sizeId" id="">
                            {% for item in sizes %}
                                <option class="colorsSelect " value="{{item.id}}">{{item.size}}</option>
                            {% endfor %}
                        </select>
                        <button class="btn btn-green rounded-1 ml-3">Добавить</button>
                    </form>
                </div>
            </div>
            <div class="hr-dark-light"></div>
             
            <div class="grid-4 gap-1">
                {% for item in productColor.product_productsColors.all %}
                    <div class="">
                        <div class=" box p-3 initial_form border-dark-light rounded-1 grid-2 gap-1" >
                            <input type="price" value="{{item.price}}" disabled class="input refreshPrice">
                            <input type="price" value="{{item.memory}}GB" disabled class="input ">
    
                            <button type="button" class="productColorSizeEditBtn btn btn-green rounded-1">Изменить</button>
                            <button type="button" data-url="{% url 'productColorSize_delete' %}" data-id="{{item.id}}" class="productColorSizeDeleteBtn btn btn-red rounded-1">Удалить</button>
                        </div>
                        <!-- Back -->
                        <div class="d-none form_edit box p-3 border-dark-light rounded-1 grid-2 gap-1" >
                            <input type="price" value="{{item.price}}"  class="input input_price">
                            <input type="price" value="{{item.memory}}GB" disabled class="input ">
    
                            <button type="button" data-id="{{item.id}}" data-url="{% url 'productColorSize_edit' %}"  class="productColorSize_edit btn btn-green rounded-1">Сохранить</button>
                            <button type="button" class="productColorSizeCancelBtn btn btn-grey rounded-1">Назад</button>
                        </div>
                    </div>
                {% endfor %}
            </div>

    
        </div>
    </div>
</div>

{% endblock %}

demo/app/templates/pages/admin/product.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Settings {% endblock %}

{% block content %}
   <!-- Main -->


    <div class="bg-light settings-page py-4 min-vh-100 bg-sm-none ">
        <div class="container">
            {% include 'pages/settings/menu.html' %}
            <div class="shadow-2 bg-white rounded-1 p-4 mt-4 p-sm-0 ">
                    <div class="d-flex align-items-center justify-content-between">
                        <div class="fs-30 b-1">Продукты</div>
                        <a class="btn btn-green rounded-1" href="{% url 'product_create' %}">Добавить продукт</a>
                    </div>
                    <div class="hr-dark-light"></div>
                    <table class="table table-light">
                        <thead>
                            <tr>
                                <td class="text-center">#</td>
                                <td>Наименование</td>
                                <td>Цвет</td>
                                <td>Действие</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in products %}
                            <tr>
                                <td class="text-center"><div class="p-3 border-dark-light rounded-1">{{forloop.counter}}</div></td>
                                <td><div class="p-3 border-dark-light rounded-1">{{product.title}}</div></td>
                                <td>
                                    <div class="d-flex">
                                        {% for item in product.productcolor_set.all %}
                                            <a href="{% url 'admin_product_detail' item.id %}" class="b-1 mr-2 p-3 border-dark-light rounded-1">{{item.color}}</a>
                                        {% endfor %}
                                    </div>
                                </td>
                                <td>
                                    <div class="d-flex">
                                        <a href="{% url 'productColor_create' product.id %}" class="btn  btn-blue rounded-1">Посмотреть</a>
                                        <button data-id="{{product.id}}" data-img="{{product.image.url}}" class="btn btnMain photo  btn-yellow rounded-1 ml-2">Фото</button>
                                    </div>

                                </td>
                            </tr>
                            {% endfor %}
                            <div class="modal-container modalMain d-none">
                                <div class="modal p-3">
                                    <img  class="w-100" src="" alt="">
                                    <form class="mt-3 form" action="" enctype="multipart/form-data" method="POST">
                                        {% csrf_token %}
                                        <label class="label" for="image">Выберите фото</label>
                                        <input class="input" name="image" id="image" type="file">
                                        <button class="btn btn-green rounded-1 w-100 mt-2">Изменить</button>
                                    </form>
                                </div>
                            </div>
                        </tbody>
                    </table>
            </div>
        </div>
    </div>


{% endblock %}

demo/app/templates/pages/admin/storage-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Storage Detail{% endblock %}

{% block content %}
   <!-- Main -->

   
    <div class="bg-light settings-page min-vh-100 bg-sm-none">
        <div class="container py-4">
            {% include 'pages/settings/menu.html' %}
            <div class="bg-white py-4 px-3 rounded-1 mt-4">
                <table id="myTable2" class="table table-light editRefresh">
                    <thead>
                        <tr>
                            <td class="text-center">#</td>
                            <td>Наименование</td>
                            <td>GB</td>
             
                            <td>Кол-во</td>
                            <td>Статус</td>
                            <td>Дата</td>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Product Color -->
                        {% for item in storage %}
                        <tr>
                            <td class="text-center">{{forloop.counter}}</td>
                            <td>{{item.productColorSize}}</td>
                            <td>{{item.productColorSize.memory}}GB</td>
                        
                            <td>{{item.quantity}}</td>
                            <td>
                                {% if item.storage_type == True %}
                                    Приход
                                {% else %}
                                    Расход
                                {% endif %}
                            </td>
                            <td>
                                {{item.date}}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
         

        </div>
    </div>


{% endblock %}

demo/app/templates/pages/admin/storage.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Storage {% endblock %}

{% block content %}
   <!-- Main -->

   
    <div class="bg-light settings-page min-vh-100 bg-sm-none">
        <div class="container py-4">
            {% include 'pages/settings/menu.html' %}
            <div class="bg-white py-4 px-3 rounded-1 mt-4">
                <table id="myTable" class="table table-light editRefresh">
                    <thead>
                        <tr>
                            <td class="text-center">#</td>
                            <td>Наименование</td>
                            <td>GB</td>
             
                            <td>Кол-во</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Product Color -->
                        {% for item in products %}
                         
                            <tr>
                                <td class="text-center">{{forloop.counter}}</td>
                                <td>{{item.productColor}}</td>
                                <td>{{item.memory}}GB</td>
                            
                                <td>{{item.real_count}}</td>
                                <td>
                                    <div class="grid-2 gap-1">
                                        <button id="{{item.id}}" class="storageModal btn btn-blue rounded-1">Обновить</button>
                                        <a href="{% url 'storage_detail' item.id %}" class=" btn btn-grey rounded-1">Посмотреть</a>
                                    </div>
                                </td>
                            </tr>
                         
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="modal-container d-none storageModalContainer">
                <div class="modal p-3">
                    <form action="" class="form grid-1 gap-1" method="POST">
                        {% csrf_token %}
                        <div class="">
                            <label class="label" for="">Кол-во</label>
                            <input type="number" name="quantity" class="input">
                        </div>
                        <div class="">
                            <label class="label" for="">Кол-во</label>
                            <select name="answer"  class="input">
                                <option value="True">Приход</option>
                                <option value="False">Расход</option>
                            </select>
                        </div>
                        <button class=" btn btn-blue rounded-1">Сохранить</button>

                    </form>
                </div>
            </div>

        </div>
    </div>


{% endblock %}