demo/app/urls.py
from unicodedata import name
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('sign-in', views.sign_in, name='sign_in'),
    path('sign-up', views.sign_up, name='sign_up'),
    path('sign-out', views.sign_out, name='sign_out'),

    path('product/<int:id>', views.product_detail, name='product_detail'),

    path('cart/', views.cart, name='cart'),
    path('addToCart/', views.addToCart, name='addToCart'),
    path('cartPlus/', views.cartPlus, name='cartPlus'),
    path('cartMinus/', views.cartMinus, name='cartMinus'),

    path('new-order/', views.new_order, name='new_order'),
    path('order-detail/<int:id>/', views.order_detail, name='order_detail'),


    path('settings/index.html', views.settings, name='settings'),


    # Admin panel
    path('user/product', views.admin_product, name='admin_product'),
    path('user/product-image/<int:id>/', views.admin_product_image_edit, name='admin_product_image_edit'),

    path('user/product-color/<int:id>', views.admin_product_detail, name='admin_product_detail'),
    path('user/create/product', views.product_create, name='product_create'),
    
    # Product Color 
    path('user/create/productColor/<int:id>/', views.productColor_create, name='productColor_create'),
    path('user/delete/productColor/<int:id>/', views.productColor_delete, name='productColor_delete'),

    # Product Color size
    path('user/create/productColorSize/<int:id>/', views.productColorSize_create, name='productColorSize_create'),
    path('user/delete/productColorSize/', views.productColorSize_delete, name='productColorSize_delete'),
    path('user/edit/productColorSize/', views.productColorSize_edit, name='productColorSize_edit'),


    # Product Color Size Gallery

    path('user/gallery/productColor/<int:id>/', views.productColor_gallery, name='productColor_gallery'),
    path('user/gallery/productColor/<int:id>/create', views.productColor_gallery_create, name='productColor_gallery_create'),
    path('user/gallery/productColor/remove', views.productColor_gallery_remove, name='productColor_gallery_remove'),

    # Storage
    path('storage/', views.storage, name='storage'),
    path('storage-detail/<int:id>/', views.storage_detail, name='storage_detail'),
    path('storage/<int:id>/', views.storage_reload, name='storage_reload')




    
]

demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

demo/app/models.py
from tabnanny import verbose
from django.utils import timezone
from django.db import models
from django.conf import settings
User = settings.AUTH_USER_MODEL



class Category(models.Model):
    title = models.CharField('Категория товара', max_length=256)
    icon = models.ImageField('Иконка', upload_to='category_icons', blank=True)


    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


class Brand(models.Model):
    title = models.CharField('Бренд товара', max_length=256)
    image = models.ImageField('Логотип', upload_to='product_logos', blank=True)


    class Meta:
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренды'

    def __str__(self):
        return self.title


class Color(models.Model):
    title = models.CharField('Цвет', max_length=256)
    code = models.CharField('Hex', max_length=256, null=True)


    class Meta:
        verbose_name = 'Цвет'
        verbose_name_plural = 'Цвета'

    def __str__(self):
        return self.title



class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория', related_name='category_products')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, verbose_name='Бренд', related_name='brand_products')
    title = models.CharField('Название товара', max_length=256)
    text = models.TextField('Описание')
    year = models.IntegerField(default=0)
    image = models.ImageField('Фото', upload_to='product_image', blank=True)
    created_at = models.DateTimeField('Дата создания',default=timezone.now())
    color = models.ManyToManyField(Color, verbose_name='Цвет', through="ProductColor")



    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты(общий)'

    def __str__(self):
        return self.title


    
class Memory(models.Model):
    size = models.IntegerField('Память', default=0)


    class Meta:
        verbose_name = 'Память'
        verbose_name_plural = 'Память'

    def __str__(self):
        return str(self.size)




class ProductColor(models.Model):
    color = models.ForeignKey(Color, on_delete=models.CASCADE, verbose_name='Цвет', related_name='color_products')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')


    class Meta:
        verbose_name = 'Product color'
        verbose_name_plural = 'Product color'

    def __str__(self):
        return self.product.title + ' ' + self.color.title


class ProductGallery(models.Model):
    productColor = models.ForeignKey(ProductColor, on_delete=models.CASCADE, verbose_name='Продукт', related_name='gallery_products')
    image = models.ImageField('Фото продукта', upload_to='productColor_gallery', blank=True)

    class Meta:
        verbose_name = 'Галерея'
        verbose_name_plural = 'Галерея'

    def __str__(self):
        return self.productColor.product.title


class ProductColorSize(models.Model):
    productColor = models.ForeignKey(ProductColor, on_delete=models.CASCADE, verbose_name='Продукт', related_name='product_productsColors')
    memory = models.ForeignKey(Memory, null=True,  on_delete=models.CASCADE, verbose_name='Память', related_name='memory_productsColors')
    price = models.IntegerField('Цена', default=0)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


    def real_count(self):
        income = sum([storage.quantity for storage in self.storage_set.filter(storage_type = True)])
        consumption = sum([storage.quantity for storage in self.storage_set.filter(storage_type = False)])
        result = income - consumption
        return result

    def __str__(self):
        return  str(self.productColor.product) + ' ' + str(self.memory)+ 'GB' + ' ' + str(self.productColor.color.title)



class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Юзер', related_name='user_carts' )
    product = models.ForeignKey(ProductColorSize, on_delete=models.CASCADE, verbose_name='Продукт', related_name='cart_products')
    quantity = models.IntegerField('Кол-во', default=0)

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзина'

    def __str__(self):
        return str(self.user) + " " + str(self.product)



class Order(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, verbose_name='Юзер', related_name='user_orders' )
    total = models.IntegerField('Total', default=0)
    status = models.BooleanField('Status', default=False)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказ'

    def __str__(self):
        return str(self.user) 


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete = models.CASCADE)
    product = models.ForeignKey(ProductColorSize, on_delete = models.SET_NULL, null=True)
    product_count = models.IntegerField('Количество', default=0)

    class Meta:
        verbose_name = 'Order Product'
        verbose_name_plural = 'Order Product'

    def __str__(self):
        return str(self.product) 



class Storage(models.Model):
    quantity = models.IntegerField('Кол-во товара в наличии', default = 0)  
    productColorSize = models.ForeignKey(ProductColorSize, on_delete = models.SET_NULL,   null=True, verbose_name="Продукт")   
    storage_type = models.BooleanField(default=False) 
    date = models.DateTimeField('Дата', default = timezone.now)

demo/app/templates/pages/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}
   <!-- Main -->
  
  <div class="bg-light  min-vh-100 pt-4">
    <div class="bg-white shadow-2 rounded-1 p-4 container ">
      <div class="inner-shadow-2 fs-30 p-3 rounded-1">Корзина</div>
      <div class="d-flex mt-4 align-items-start">
          <div class="left grid-1 gap-1 w-70   rounded-1">
            {% for item in cart %}
                <div class="inner-shadow-2 p-3 rounded-1">
                    <div class="d-flex align-items-center">
                        <div class="">
                            <div class="fs-18 b-1">
                                {{item.product.productColor.product.title}}
                            </div>
                            <a href="{{item.product.productColor.product.image.url}}" class="w-15 d-block">
                                <img class="w-100" src="{{item.product.productColor.product.image.url}}" alt="">
                            </a>
                        </div>
                        <div class="counting d-flex align-items-center">
                            <button  data-url="{% url 'cartMinus' %}" data-id="{{item.id}}" class="btn btn-grey cartMinus  rounded-1"><i class='bx bx-minus'></i></button>
                            <div class="mx-2 cart_input_parent">
                                <input readonly  class="input cart_input_child{{item.id}} " value="{{item.quantity}}" type="text">
                            </div>
                            <button data-url="{% url 'cartPlus' %}" data-id="{{item.id}}" class="btn btn-grey cartPlus rounded-1"><i class='bx bx-plus'></i></button>
                        </div>
                        <div  class="fs-20 b-2 ml-3 "><span id="{{item.id}}" class="cart_price">{{item.product.price}}</span>$</div>
                    </div>
                </div>
            {% endfor %}
          </div>
          <div class="right w-25 p-3 inner-shadow-2 rounded-1 ml-auto">
              <div class="fs-23 b-2">Корзина</div>
              
              <div class="hr-dark-light"></div>
              <div class="fs-16 b-2">Сумма: <span class="cart_quant"></span></div>
              <div class="fs-16 b-2">Кол-во: <span class="cart_quant"></span></div>
              <div class="fs-16 b-2">Доставка: <span class="cart_quant"></span></div>
              <div class="hr-dark-light"></div>
              <form action="{% url 'new_order' %}"  class="d-flex align-items-center" method="POST">
                {% csrf_token %}
                <div class="fs18 b-2">Итого: <span class="cart_total"></span>$</div>
                <button class="btn btn-sm btn-orange rounded-1 ml-auto">Оформить заказ</button>
                <input class="d-none hidden_total" name="total" type="text">
              </form>
          </div>
      </div>
  </div>

{% endblock %}

demo/app/templates/pages/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}
   <!-- Main -->
  
  <div class="bg-light min-vh-100 pt-4">
    <div class="bg-white shadow-1 rounded-1 p-4 container ">
      <div class="grid-5 gap-1">
        {% for product in products %}
        <div class="product-box p-3 shadow-2 rounded-1">
          <img class="w-100" src="{{product.image.url}}" alt="">
          <div class="fs-18 b-1 mb-3">{{product.title}}</div>
          <div class="hr-dark-night mt-0"></div>
          <a href="{% url 'product_detail' product.id %}" class="btn btn-blue rounded-1">Посмотреть</a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}

demo/app/templates/pages/order.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}
   <!-- Main -->
  
  <div class="bg-light min-vh-100 pt-4">
    <div class="bg-white rounded-1 p-4 container ">
      <div class="d-flex gap-1">
        <div class="uzcard w-70 p-4 rounded-1 shadow-2 bg-night"></div>
        <div class="total w-30 p-4 rounded-1 inner-shadow-2">
            <div class="fs-23 b-2">Заказ</div>
            <div class="hr-dark-light"></div>
            {% for product in order.orderproduct_set.all %}
            <div class="">{{product.product}}</div>
            {% endfor %}
            <div class="hr-dark-light"></div>
            <div class="fs-16 b-2">Сумма: <span class="cart_quant"></span></div>
            <div class="fs-16 b-2">Кол-во: <span class="cart_quant"></span></div>
            <div class="fs-16 b-2">Доставка: <span class="cart_quant"></span></div>
            <div class="hr-dark-light"></div>
            <div class="d-flex align-items-center">
              <div class="fs18 b-2">Итого: {{order.total}}<span class=""></span>$</div>
            </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

demo/app/templates/pages/product-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{product.title}} {% endblock %}

{% block content %}
   <!-- Main -->

  <div class="bg-light  ">
    <div class="container product_detail_container py-4">
        <div class="bg-white shadow-3 rounded-1 p-4">
            <div class="grid-2 gap-2">
              <div class="left ">
                  <div class="shadow-2 rounded-2 p-3 mb-4">
                    <img class="w-100 rounded-top-left-2 rounded-top-right-2" src="{{product.image.url}}" alt="">
                  </div>
                  <div class="inner-shadow-2 grid-4 gap-1 mt-3  p-3 rounded-2">
                    <img class="w-100  rounded-1" src="{{product.image.url}}" alt="">

                  </div>
              </div>
              <div class="right product_detail">
                <div class="inner-shadow-2 rounded-2 p-3">
                    <div class="d-flex align-items-center">
                        <div class="title b-2 fs-26">{{product.title}}</div>
                        <div class="fs-26 brand b-2 ml-auto">{{product.brand}}</div>
                    </div>
                    <div class="mt-4 b-2 fs-18">Description:</div>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet minima natus obcaecati omnis assumenda mollitia hic dolore. Sunt, iusto distinctio dignissimos quos laborum odit, rerum veniam ipsum consectetur dolor saepe?
                    </p>
                   
                  
                </div>
                {% for productColor in productColors %}
                <div class="my-4 d inner-shadow-2 p-3 rounded-2 b-2 fs-17">{{ productColor.color }}</div>
                <div class="shadow-2 p-3 rounded-2 inner-shadow-2">
                    <div class="grid-4 gap-1">
                        {% for size in productColor.product_productsColors.all %}
                  
                            {% if size.price == 0 %}
                            <!-- <div class="scene rounded-2 ">
                                <div class="box">
                                    <div class="front bg-white shadow-2 rounded-2 b-2 fs-20 d-flex align-items-center justify-content-center">{{size.memory}}GB</div>
                                    <div class="back d-flex flex-column justify-content-center align-items-center rounded-2 bg-dark-night text-light">
                                        <div class="fs-20">Нет в наличии</div>
                                        <button data-url="{% url 'addToCart' %}" data-id="{{size.id}}" class="addToCart btn btn-light btn-sm rounded-1 mt-2 b-1">В корзину</button>
                                    </div>
                                </div>
                            </div> -->
                            {% else %}
                            <div class="scene rounded-2 ">
                                <div class="box">
                                    <div class="front bg-white shadow-2 rounded-2 b-2 fs-20 d-flex align-items-center justify-content-center">{{size.memory}}GB</div>
                                    <div class="back d-flex flex-column justify-content-center align-items-center rounded-2 bg-dark-night text-light">
                                        {% if size.real_count == 0 %}
                                        <div class="fs-13"> Нет в Наличии</div>
                                        {% else %}
                                        <div class="fs-20">{{size.price}}$</div>
                                        <button data-url="{% url 'addToCart' %}" data-id="{{size.id}}" class="addToCart btn btn-light btn-sm rounded-1 mt-2 b-1">В корзину</button>

                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
    </div>
  </div>

  <script>
      let cards = document.querySelectorAll('.box')
      for(let card of cards){
          card.addEventListener('click', ()=> {
              card.classList.toggle('active')
          })
      }
  </script>
{% endblock %}

demo/app/templates/pages/sign_in.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}
   
<div class="container">
    <div class="sign_in_container py-4 grid-2 ">
        <div class="left d-flex bg-dark-night text-light justify-content-center  align-items-center">
            <section class="copy">
                <h1>Codify Labs</h1>
                <p>Over 1000 projects taught by real creatives</p>
            </section>
        </div>
        <div class="right d-flex justify-content-center align-items-center">
            <form action="{% url 'sign_in' %}" method="POST">
                {% csrf_token %}
                <section class="bg-dark copy text-center text-dark-night">
                    <h2>Sign in</h2>
                    <div class="login-container">
                        <p class="my-4  fs-14">
                            Don't have an accounts?
                            <a href="{% url 'sign_up' %}" class="b-1 text-blue">Sign up</a>
                        </p>
                    </div>
                </section>
                <div class="my-4">
                    <label for="fname">Email</label>
                    <input id="fname" class="input input-md" name="username" type="email">
                </div>
                <div class="my-4">
                    <label for="fname">Password</label>
                    <input id="fname" class="input input-md" name="password" type="password">
                </div>
                <button class="btn btn-night btn-md w-100 rounded-1">Sign in</button>
                
                <!-- <section>
                    <p class="small text-center fs-13">
                        <span >
                            By continuing, you agree to accept our <br> 
                            <a href="#" class="text-blue">
                                Privacy Policy 
                            </a>
                            &amp; 
                            <a href="#" class="text-blue">Terms of Servicy </a>.
                        </span>
                    </p>
                </section>  -->
            </form>
        </div>
    </div>
</div>
   

{% endblock %}

demo/app/templates/pages/sign_up.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}
   
<div class="container">
    <div class="sign_in_container py-4 grid-2 ">
        <div class="left d-flex text-light bg-dark-night justify-content-center align-items-center">
            <section class="copy">
                <h1>Codify Labs</h1>
                <p>Over 1000 projects taught by real creatives</p>
            </section>
        </div>
        <div class="right d-flex justify-content-center align-items-center">
            <form action="{% url 'sign_up' %}" method="POST">
                {% csrf_token %}
                <section class="copy text-center text-dark-night">
                    <h2>Sign up</h2>
                    <div class="login-container">
                        <p class="my-4  fs-14">
                            Already have an accounts?
                            <a href="{% url 'sign_in' %}" class="b-1 text-blue">Sign in</a>
                        </p>
                    </div>
                </section>
                <div class="my-4">
                    <label for="fname">Email</label>
                    {{form.email}}
                </div>
                <div class="my-4">
                    <label for="fname">Password</label>
                    {{form.password1}}
                </div>
                <div class="my-4">
                    <label for="fname">Password</label>
                    {{form.password2}}
                </div>
                <button class="btn btn-night btn-md w-100 rounded-1">Sign up</button>
                
                <section>
                    <p class="small text-center fs-13">
                        <span >
                            By continuing, you agree to accept our <br> 
                            <a href="#" class="text-blue">
                                Privacy Policy 
                            </a>
                            &amp; 
                            <a href="#" class="text-blue">Terms of Servicy </a>.
                        </span>
                    </p>
                </section> 
                {% for message in messages %}
                    <div class="p-2 border-red rounded-1 my-2">
                        {{message}}
                    </div>
                {% endfor %}
            </form>
        </div>
    </div>
</div>
   

{% endblock %}